export const FETCH_FILMS = 'FETCH_FILMS';

export const FETCH_FILM = 'FETCH_FILM';

export const FETCH_STARSHIPS = 'FETCH_STARSHIPS';

export const RECEIVE_CHARACTER = "RECEIVE_CHARACTER";
export const RESET_CHARACTERS = "RESET_CHARACTERS";

export const RECEIVE_PLANETS = "RECEIVE_PLANETS";
export const RESET_PLANETS = "RESET_CHARACTERS";

export const RECEIVE_SPECIES = "RECEIVE_SPECIES";
export const RESET_SPECIES = "RESET_SPECIES";

export const RECEIVE_VEHICLES ="RECEIVE_VEHICLES";
export const RESET_VEHICLES="RESET_VEHICLES";


